/**
 * NutriChoice Food Database
 * Contains nutritional information for 50 foods across 5 categories:
 * - Fruits
 * - Vegetables
 * - Proteins
 * - Grains
 * - Dairy
 */

const foodData = [
    // FRUITS
    {
        id: 1,
        name: "Apple",
        category: "fruit",
        calories: 52,
        nutrients: {
            protein: 0.3,
            carbs: 14,
            fat: 0.2,
            fiber: 2.4,
            vitaminA: 2,
            vitaminC: 8,
            vitaminD: 0,
            vitaminE: 2,
            calcium: 1,
            iron: 1,
            potassium: 3,
            magnesium: 1,
            omega3: 0,
            antioxidants: 7
        },
        description: "A crisp, sweet fruit that's high in fiber and vitamin C. Apples contain antioxidants that may help reduce the risk of chronic diseases.",
        image: "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 2,
        name: "Banana",
        category: "fruit",
        calories: 89,
        nutrients: {
            protein: 1.1,
            carbs: 23,
            fat: 0.3,
            fiber: 2.6,
            vitaminA: 1,
            vitaminC: 14,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 2,
            potassium: 10,
            magnesium: 8,
            omega3: 0,
            antioxidants: 4
        },
        description: "An energy-packed fruit rich in potassium and vitamin B6. Bananas support heart health and provide sustained energy for physical activity.",
        image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 3,
        name: "Blueberries",
        category: "fruit",
        calories: 57,
        nutrients: {
            protein: 0.7,
            carbs: 14.5,
            fat: 0.3,
            fiber: 2.4,
            vitaminA: 1,
            vitaminC: 24,
            vitaminD: 0,
            vitaminE: 5,
            calcium: 1,
            iron: 2,
            potassium: 2,
            magnesium: 1,
            omega3: 0,
            antioxidants: 9
        },
        description: "Small but mighty berries with one of the highest antioxidant levels of common fruits. They support brain health and may improve memory.",
        image: "https://images.unsplash.com/photo-1598840639709-44a0aeb6ee2c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 4,
        name: "Avocado",
        category: "fruit",
        calories: 160,
        nutrients: {
            protein: 2,
            carbs: 8.5,
            fat: 15,
            fiber: 7,
            vitaminA: 2,
            vitaminC: 17,
            vitaminD: 0,
            vitaminE: 14,
            calcium: 1,
            iron: 3,
            potassium: 14,
            magnesium: 7,
            omega3: 1,
            antioxidants: 6
        },
        description: "A nutrient-dense fruit rich in healthy fats, fiber, and potassium. Avocados support heart health and help with nutrient absorption.",
        image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 5,
        name: "Orange",
        category: "fruit",
        calories: 47,
        nutrients: {
            protein: 0.9,
            carbs: 12,
            fat: 0.1,
            fiber: 2.4,
            vitaminA: 4,
            vitaminC: 89,
            vitaminD: 0,
            vitaminE: 3,
            calcium: 4,
            iron: 1,
            potassium: 5,
            magnesium: 2,
            omega3: 0,
            antioxidants: 7
        },
        description: "Juicy citrus fruit known for its high vitamin C content. Oranges support immune function and skin health with their antioxidant properties.",
        image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 6,
        name: "Strawberries",
        category: "fruit",
        calories: 32,
        nutrients: {
            protein: 0.7,
            carbs: 7.7,
            fat: 0.3,
            fiber: 2,
            vitaminA: 0,
            vitaminC: 98,
            vitaminD: 0,
            vitaminE: 3,
            calcium: 2,
            iron: 2,
            potassium: 5,
            magnesium: 2,
            omega3: 0,
            antioxidants: 8
        },
        description: "Sweet berries that are packed with vitamin C and antioxidants. Strawberries support heart health and have anti-inflammatory properties.",
        image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 7,
        name: "Mango",
        category: "fruit",
        calories: 60,
        nutrients: {
            protein: 0.8,
            carbs: 15,
            fat: 0.4,
            fiber: 1.6,
            vitaminA: 18,
            vitaminC: 60,
            vitaminD: 0,
            vitaminE: 6,
            calcium: 1,
            iron: 1,
            potassium: 4,
            magnesium: 2,
            omega3: 0,
            antioxidants: 7
        },
        description: "Tropical fruit rich in vitamins A and C. Mangoes support eye health and immunity while providing a sweet, tropical flavor.",
        image: "https://images.unsplash.com/photo-1605027725193-1ce116629dd6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 8,
        name: "Grapes",
        category: "fruit",
        calories: 69,
        nutrients: {
            protein: 0.6,
            carbs: 18,
            fat: 0.2,
            fiber: 0.9,
            vitaminA: 1,
            vitaminC: 14,
            vitaminD: 0,
            vitaminE: 2,
            calcium: 1,
            iron: 1,
            potassium: 5,
            magnesium: 1,
            omega3: 0,
            antioxidants: 8
        },
        description: "Small clusters of juicy berries rich in antioxidants like resveratrol. Grapes support heart health and may have anti-aging benefits.",
        image: "https://images.unsplash.com/photo-1596363505729-4190a9db9c6a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 9,
        name: "Kiwi",
        category: "fruit",
        calories: 61,
        nutrients: {
            protein: 1.1,
            carbs: 15,
            fat: 0.5,
            fiber: 3,
            vitaminA: 3,
            vitaminC: 93,
            vitaminD: 0,
            vitaminE: 7,
            calcium: 3,
            iron: 2,
            potassium: 7,
            magnesium: 3,
            omega3: 0,
            antioxidants: 7
        },
        description: "Small fruit with fuzzy skin and bright green flesh, packed with vitamin C. Kiwis support immune health and aid in digestion.",
        image: "https://images.unsplash.com/photo-1618897996318-5a901fa6ca71?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 10,
        name: "Pineapple",
        category: "fruit",
        calories: 50,
        nutrients: {
            protein: 0.5,
            carbs: 13,
            fat: 0.1,
            fiber: 1.4,
            vitaminA: 1,
            vitaminC: 79,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 2,
            potassium: 3,
            magnesium: 3,
            omega3: 0,
            antioxidants: 6
        },
        description: "Tropical fruit with sweet-tart flavor and enzyme bromelain. Pineapples aid digestion and have anti-inflammatory properties.",
        image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    
    // VEGETABLES
    {
        id: 11,
        name: "Broccoli",
        category: "vegetable",
        calories: 34,
        nutrients: {
            protein: 2.8,
            carbs: 7,
            fat: 0.4,
            fiber: 2.6,
            vitaminA: 12,
            vitaminC: 148,
            vitaminD: 0,
            vitaminE: 5,
            calcium: 5,
            iron: 3,
            potassium: 8,
            magnesium: 5,
            omega3: 0,
            antioxidants: 8
        },
        description: "Nutrient-dense cruciferous vegetable high in vitamins C and K. Broccoli contains compounds that may help prevent cancer and support detoxification.",
        image: "https://images.unsplash.com/photo-1584270354949-c26b0d5b4a0c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 12,
        name: "Spinach",
        category: "vegetable",
        calories: 23,
        nutrients: {
            protein: 2.9,
            carbs: 3.6,
            fat: 0.4,
            fiber: 2.2,
            vitaminA: 56,
            vitaminC: 28,
            vitaminD: 0,
            vitaminE: 10,
            calcium: 10,
            iron: 15,
            potassium: 12,
            magnesium: 20,
            omega3: 0,
            antioxidants: 9
        },
        description: "Leafy green vegetable packed with iron, calcium, and antioxidants. Spinach supports bone health, improves eye health, and boosts immunity.",
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 13,
        name: "Kale",
        category: "vegetable",
        calories: 49,
        nutrients: {
            protein: 4.3,
            carbs: 8.8,
            fat: 0.9,
            fiber: 3.6,
            vitaminA: 308,
            vitaminC: 200,
            vitaminD: 0,
            vitaminE: 6,
            calcium: 15,
            iron: 8,
            potassium: 9,
            magnesium: 7,
            omega3: 0,
            antioxidants: 10
        },
        description: "Superfood leafy green that's loaded with nutrients. Kale is one of the most nutrient-dense foods on the planet, supporting overall health.",
        image: "https://images.unsplash.com/photo-1610048899856-fb721d683cb4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 14,
        name: "Carrots",
        category: "vegetable",
        calories: 41,
        nutrients: {
            protein: 0.9,
            carbs: 10,
            fat: 0.2,
            fiber: 2.8,
            vitaminA: 334,
            vitaminC: 6,
            vitaminD: 0,
            vitaminE: 2,
            calcium: 3,
            iron: 1,
            potassium: 7,
            magnesium: 2,
            omega3: 0,
            antioxidants: 7
        },
        description: "Orange root vegetables exceptionally high in beta-carotene. Carrots promote eye health, support immune function, and provide antioxidant benefits.",
        image: "https://images.unsplash.com/photo-1598170845058-c2eec1a2f1f1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 15,
        name: "Bell Peppers",
        category: "vegetable",
        calories: 30,
        nutrients: {
            protein: 1,
            carbs: 6,
            fat: 0.3,
            fiber: 2.1,
            vitaminA: 18,
            vitaminC: 200,
            vitaminD: 0,
            vitaminE: 4,
            calcium: 1,
            iron: 2,
            potassium: 5,
            magnesium: 2,
            omega3: 0,
            antioxidants: 8
        },
        description: "Colorful, crunchy vegetables with high vitamin C content. Bell peppers support skin health, boost immunity, and provide a variety of antioxidants.",
        image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 16,
        name: "Sweet Potato",
        category: "vegetable",
        calories: 86,
        nutrients: {
            protein: 1.6,
            carbs: 20,
            fat: 0.1,
            fiber: 3,
            vitaminA: 384,
            vitaminC: 33,
            vitaminD: 0,
            vitaminE: 4,
            calcium: 3,
            iron: 3,
            potassium: 14,
            magnesium: 6,
            omega3: 0,
            antioxidants: 8
        },
        description: "Starchy root vegetable with vibrant orange flesh rich in beta-carotene. Sweet potatoes support eye and gut health while providing steady energy.",
        image: "https://images.unsplash.com/photo-1596097635121-14b70a3ec63a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 17,
        name: "Tomatoes",
        category: "vegetable",
        calories: 18,
        nutrients: {
            protein: 0.9,
            carbs: 3.9,
            fat: 0.2,
            fiber: 1.2,
            vitaminA: 17,
            vitaminC: 21,
            vitaminD: 0,
            vitaminE: 4,
            calcium: 1,
            iron: 1,
            potassium: 6,
            magnesium: 2,
            omega3: 0,
            antioxidants: 9
        },
        description: "Juicy fruits botanically, but culinary vegetables rich in lycopene. Tomatoes support heart health and have cancer-fighting properties.",
        image: "https://images.unsplash.com/photo-1561136594-7f68413baa99?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 18,
        name: "Cauliflower",
        category: "vegetable",
        calories: 25,
        nutrients: {
            protein: 2,
            carbs: 5,
            fat: 0.3,
            fiber: 2.5,
            vitaminA: 0,
            vitaminC: 77,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 2,
            iron: 2,
            potassium: 9,
            magnesium: 3,
            omega3: 0,
            antioxidants: 7
        },
        description: "Versatile cruciferous vegetable with impressive nutrient content. Cauliflower supports detoxification and has anti-inflammatory properties.",
        image: "https://images.unsplash.com/photo-1510627498534-cf7e9002facc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 19,
        name: "Cucumber",
        category: "vegetable",
        calories: 15,
        nutrients: {
            protein: 0.7,
            carbs: 3.6,
            fat: 0.1,
            fiber: 0.5,
            vitaminA: 2,
            vitaminC: 4,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 2,
            iron: 1,
            potassium: 4,
            magnesium: 3,
            omega3: 0,
            antioxidants: 3
        },
        description: "Refreshing vegetable with high water content. Cucumbers help with hydration, digestion, and have cooling anti-inflammatory properties.",
        image: "https://images.unsplash.com/photo-1568584711271-6c929fb49b60?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 20,
        name: "Garlic",
        category: "vegetable",
        calories: 42,
        nutrients: {
            protein: 1.8,
            carbs: 9.1,
            fat: 0.2,
            fiber: 2.1,
            vitaminA: 0,
            vitaminC: 31,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 18,
            iron: 6,
            potassium: 12,
            magnesium: 7,
            omega3: 0,
            antioxidants: 9
        },
        description: "Potent herb with powerful medicinal properties. Garlic boosts immunity, reduces blood pressure, and has antimicrobial benefits.",
        image: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    
    // PROTEINS
    {
        id: 21,
        name: "Chicken Breast",
        category: "protein",
        calories: 165,
        nutrients: {
            protein: 31,
            carbs: 0,
            fat: 3.6,
            fiber: 0,
            vitaminA: 1,
            vitaminC: 0,
            vitaminD: 1,
            vitaminE: 2,
            calcium: 1,
            iron: 5,
            potassium: 7,
            magnesium: 5,
            omega3: 1,
            antioxidants: 1
        },
        description: "Lean poultry meat high in protein and low in fat. Chicken breast supports muscle growth and provides essential B vitamins for energy.",
        image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 22,
        name: "Salmon",
        category: "protein",
        calories: 206,
        nutrients: {
            protein: 22,
            carbs: 0,
            fat: 13,
            fiber: 0,
            vitaminA: 2,
            vitaminC: 3,
            vitaminD: 66,
            vitaminE: 7,
            calcium: 1,
            iron: 2,
            potassium: 9,
            magnesium: 7,
            omega3: 10,
            antioxidants: 4
        },
        description: "Fatty fish rich in omega-3 fatty acids and high-quality protein. Salmon reduces inflammation, supports brain health, and benefits heart health.",
        image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 23,
        name: "Eggs",
        category: "protein",
        calories: 78,
        nutrients: {
            protein: 6.3,
            carbs: 0.6,
            fat: 5.3,
            fiber: 0,
            vitaminA: 6,
            vitaminC: 0,
            vitaminD: 11,
            vitaminE: 5,
            calcium: 3,
            iron: 5,
            potassium: 2,
            magnesium: 2,
            omega3: 2,
            antioxidants: 6
        },
        description: "Nutrient-dense food rich in high-quality protein. Eggs contain all essential amino acids and important nutrients for brain development and eye health.",
        image: "https://images.unsplash.com/photo-1551722699-1b6a3acc1b7b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 24,
        name: "Lentils",
        category: "protein",
        calories: 116,
        nutrients: {
            protein: 9,
            carbs: 20,
            fat: 0.4,
            fiber: 8,
            vitaminA: 0,
            vitaminC: 1,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 2,
            iron: 19,
            potassium: 10,
            magnesium: 9,
            omega3: 0,
            antioxidants: 5
        },
        description: "Plant-based protein source rich in fiber and minerals. Lentils help stabilize blood sugar, support heart health, and provide sustained energy.",
        image: "https://images.unsplash.com/photo-1611575619951-2ddb6c731e5a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 25,
        name: "Black Beans",
        category: "protein",
        calories: 132,
        nutrients: {
            protein: 8.9,
            carbs: 24,
            fat: 0.6,
            fiber: 8.7,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 3,
            iron: 10,
            potassium: 11,
            magnesium: 14,
            omega3: 0,
            antioxidants: 8
        },
        description: "Nutrient-dense legumes rich in protein and fiber. Black beans support digestive health, provide steady energy, and contain antioxidants.",
        image: "https://images.unsplash.com/photo-1590686910899-43ecd87ef617?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 26,
        name: "Tofu",
        category: "protein",
        calories: 76,
        nutrients: {
            protein: 8,
            carbs: 2,
            fat: 4.2,
            fiber: 0.6,
            vitaminA: 2,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 35,
            iron: 6,
            potassium: 4,
            magnesium: 9,
            omega3: 2,
            antioxidants: 3
        },
        description: "Versatile plant protein made from soybeans. Tofu is rich in isoflavones that may reduce heart disease risk and improve bone health.",
        image: "https://images.unsplash.com/photo-1583495838052-7da01ba1b9b2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 27,
        name: "Turkey",
        category: "protein",
        calories: 189,
        nutrients: {
            protein: 29,
            carbs: 0,
            fat: 7.4,
            fiber: 0,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 7,
            potassium: 8,
            magnesium: 5,
            omega3: 1,
            antioxidants: 1
        },
        description: "Lean poultry meat rich in protein and B vitamins. Turkey supports muscle maintenance and provides tryptophan that helps with mood regulation.",
        image: "https://images.unsplash.com/photo-1637169729356-5baf0a750a49?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 28,
        name: "Tuna",
        category: "protein",
        calories: 109,
        nutrients: {
            protein: 24,
            carbs: 0,
            fat: 0.9,
            fiber: 0,
            vitaminA: 2,
            vitaminC: 0,
            vitaminD: 39,
            vitaminE: 3,
            calcium: 1,
            iron: 4,
            potassium: 9,
            magnesium: 9,
            omega3: 7,
            antioxidants: 2
        },
        description: "Lean fish with high protein content and omega-3 fatty acids. Tuna supports heart health, aids weight management, and provides essential nutrients.",
        image: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 29,
        name: "Chickpeas",
        category: "protein",
        calories: 164,
        nutrients: {
            protein: 8.9,
            carbs: 27,
            fat: 2.6,
            fiber: 7.6,
            vitaminA: 1,
            vitaminC: 2,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 5,
            iron: 14,
            potassium: 8,
            magnesium: 12,
            omega3: 0,
            antioxidants: 6
        },
        description: "Versatile legumes high in protein and fiber. Chickpeas help manage blood sugar, support digestive health, and provide sustainable energy.",
        image: "https://images.unsplash.com/photo-1515543904379-3d757afe72e2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 30,
        name: "Almonds",
        category: "protein",
        calories: 161,
        nutrients: {
            protein: 6,
            carbs: 6,
            fat: 14,
            fiber: 3.5,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 37,
            calcium: 8,
            iron: 6,
            potassium: 6,
            magnesium: 20,
            omega3: 0,
            antioxidants: 8
        },
        description: "Nutrient-dense nuts rich in healthy fats and vitamin E. Almonds support heart health, help manage weight, and benefit brain function.",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    
    // GRAINS
    {
        id: 31,
        name: "Quinoa",
        category: "grain",
        calories: 120,
        nutrients: {
            protein: 4.4,
            carbs: 21.3,
            fat: 1.9,
            fiber: 2.8,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 8,
            potassium: 4,
            magnesium: 15,
            omega3: 0,
            antioxidants: 4
        },
        description: "Ancient grain that's actually a seed, containing all nine essential amino acids. Quinoa provides sustained energy and supports overall nutrition.",
        image: "https://images.unsplash.com/photo-1595445364671-15205e6c380c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 32,
        name: "Brown Rice",
        category: "grain",
        calories: 112,
        nutrients: {
            protein: 2.6,
            carbs: 23.5,
            fat: 0.9,
            fiber: 1.8,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 2,
            potassium: 3,
            magnesium: 11,
            omega3: 0,
            antioxidants: 3
        },
        description: "Whole grain with outer bran layer intact, providing more nutrients than white rice. Brown rice supports digestive health and provides steady energy.",
        image: "https://images.unsplash.com/photo-1536304447766-da0ed4ce1b73?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 33,
        name: "Oats",
        category: "grain",
        calories: 68,
        nutrients: {
            protein: 2.4,
            carbs: 12,
            fat: 1.4,
            fiber: 2,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 1,
            iron: 7,
            potassium: 2,
            magnesium: 8,
            omega3: 0,
            antioxidants: 5
        },
        description: "Whole grain rich in beta-glucan fiber. Oats help lower cholesterol, stabilize blood sugar, and promote feelings of fullness.",
        image: "https://images.unsplash.com/photo-1471943311424-646960669fbc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 34,
        name: "Whole Wheat Bread",
        category: "grain",
        calories: 81,
        nutrients: {
            protein: 4,
            carbs: 15,
            fat: 1.1,
            fiber: 2.4,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 2,
            calcium: 2,
            iron: 5,
            potassium: 2,
            magnesium: 4,
            omega3: 0,
            antioxidants: 2
        },
        description: "Bread made from whole wheat flour containing all parts of the grain. Whole wheat bread provides more fiber and nutrients than refined bread.",
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 35,
        name: "Barley",
        category: "grain",
        calories: 123,
        nutrients: {
            protein: 2.3,
            carbs: 28.2,
            fat: 0.4,
            fiber: 3.8,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 1,
            iron: 7,
            potassium: 2,
            magnesium: 8,
            omega3: 0,
            antioxidants: 4
        },
        description: "Ancient grain with a chewy texture and nutty flavor. Barley helps regulate blood sugar, reduce cholesterol, and support digestive health.",
        image: "https://images.unsplash.com/photo-1622697387883-3a807191c76b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 36,
        name: "Buckwheat",
        category: "grain",
        calories: 92,
        nutrients: {
            protein: 3.4,
            carbs: 20,
            fat: 0.6,
            fiber: 2.7,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 7,
            potassium: 3,
            magnesium: 13,
            omega3: 0,
            antioxidants: 6
        },
        description: "Despite its name, buckwheat is not wheat but a seed related to rhubarb. Buckwheat is gluten-free and rich in minerals and antioxidants.",
        image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 37,
        name: "Corn",
        category: "grain",
        calories: 86,
        nutrients: {
            protein: 3.2,
            carbs: 19,
            fat: 1.2,
            fiber: 2.4,
            vitaminA: 9,
            vitaminC: 7,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 0,
            iron: 2,
            potassium: 6,
            magnesium: 4,
            omega3: 0,
            antioxidants: 6
        },
        description: "Versatile grain that's technically a vegetable. Corn provides antioxidants lutein and zeaxanthin that support eye health and vision.",
        image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 38,
        name: "Whole Grain Pasta",
        category: "grain",
        calories: 124,
        nutrients: {
            protein: 5.3,
            carbs: 26,
            fat: 0.9,
            fiber: 3.2,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 8,
            potassium: 3,
            magnesium: 5,
            omega3: 0,
            antioxidants: 2
        },
        description: "Pasta made from whole wheat flour with more fiber and nutrients than refined pasta. Whole grain pasta provides steady energy and better satiety.",
        image: "https://images.unsplash.com/photo-1612966559832-f7bc6355084a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 39,
        name: "Bulgur",
        category: "grain",
        calories: 83,
        nutrients: {
            protein: 3.1,
            carbs: 18.2,
            fat: 0.2,
            fiber: 4.5,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 1,
            iron: 5,
            potassium: 2,
            magnesium: 6,
            omega3: 0,
            antioxidants: 3
        },
        description: "Parboiled cracked wheat that cooks quickly. Bulgur has a low glycemic index and supports digestive health with its fiber content.",
        image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 40,
        name: "Millet",
        category: "grain",
        calories: 119,
        nutrients: {
            protein: 3.5,
            carbs: 23.7,
            fat: 1,
            fiber: 1.3,
            vitaminA: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 1,
            iron: 6,
            potassium: 2,
            magnesium: 11,
            omega3: 0,
            antioxidants: 3
        },
        description: "Small, gluten-free grain that's easily digestible. Millet can help lower blood sugar and cholesterol while providing protective antioxidants.",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e8c6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    
    // DAIRY
    {
        id: 41,
        name: "Greek Yogurt",
        category: "dairy",
        calories: 59,
        nutrients: {
            protein: 10,
            carbs: 3.6,
            fat: 0.4,
            fiber: 0,
            vitaminA: 1,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 11,
            iron: 0,
            potassium: 4,
            magnesium: 3,
            omega3: 0,
            antioxidants: 1
        },
        description: "Strained yogurt with higher protein content than regular yogurt. Greek yogurt supports gut health with probiotics and helps with muscle recovery.",
        image: "https://images.unsplash.com/photo-1606881400491-84c10ca48909?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 42,
        name: "Milk",
        category: "dairy",
        calories: 61,
        nutrients: {
            protein: 3.2,
            carbs: 4.8,
            fat: 3.3,
            fiber: 0,
            vitaminA: 5,
            vitaminC: 0,
            vitaminD: 24,
            vitaminE: 0,
            calcium: 12,
            iron: 0,
            potassium: 5,
            magnesium: 3,
            omega3: 0,
            antioxidants: 0
        },
        description: "Nutrient-rich liquid food rich in calcium and vitamin D. Milk supports bone health and provides complete protein with all essential amino acids.",
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 43,
        name: "Cottage Cheese",
        category: "dairy",
        calories: 98,
        nutrients: {
            protein: 11.1,
            carbs: 3.4,
            fat: 4.3,
            fiber: 0,
            vitaminA: 1,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            calcium: 8,
            iron: 1,
            potassium: 4,
            magnesium: 2,
            omega3: 0,
            antioxidants: 0
        },
        description: "Fresh cheese curd product with a mild flavor and high protein content. Cottage cheese supports muscle building and provides essential nutrients.",
        image: "https://images.unsplash.com/photo-1568901839119-631418a3910d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 44,
        name: "Cheddar Cheese",
        category: "dairy",
        calories: 113,
        nutrients: {
            protein: 7,
            carbs: 0.4,
            fat: 9.3,
            fiber: 0,
            vitaminA: 10,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 2,
            calcium: 20,
            iron: 0,
            potassium: 2,
            magnesium: 1,
            omega3: 0,
            antioxidants: 1
        },
        description: "Aged hard cheese with rich flavor and high calcium content. Cheddar cheese helps strengthen bones and provides high-quality protein.",
        image: "https://images.unsplash.com/photo-1618164435735-413d3b066c9a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 45,
        name: "Kefir",
        category: "dairy",
        calories: 63,
        nutrients: {
            protein: 3.3,
            carbs: 4.6,
            fat: 3.5,
            fiber: 0,
            vitaminA: 4,
            vitaminC: 0,
            vitaminD: 1,
            vitaminE: 0,
            calcium: 12,
            iron: 0,
            potassium: 4,
            magnesium: 3,
            omega3: 0,
            antioxidants: 1
        },
        description: "Fermented milk drink with more probiotic strains than yogurt. Kefir improves gut health, boosts immunity, and can help with lactose digestion.",
        image: "https://images.unsplash.com/photo-1594143913366-d0389934aee8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 46,
        name: "Mozzarella",
        category: "dairy",
        calories: 90,
        nutrients: {
            protein: 6.3,
            carbs: 0.6,
            fat: 7,
            fiber: 0,
            vitaminA: 7,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 18,
            iron: 0,
            potassium: 1,
            magnesium: 1,
            omega3: 0,
            antioxidants: 0
        },
        description: "Fresh cheese with high moisture content and mild flavor. Mozzarella provides calcium for bone health while being lower in sodium than many cheeses.",
        image: "https://images.unsplash.com/photo-1588010254798-5a138aeef89c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 47,
        name: "Ricotta",
        category: "dairy",
        calories: 97,
        nutrients: {
            protein: 8,
            carbs: 3.8,
            fat: 4.9,
            fiber: 0,
            vitaminA: 5,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 16,
            iron: 1,
            potassium: 2,
            magnesium: 1,
            omega3: 0,
            antioxidants: 0
        },
        description: "Whey cheese with creamy texture and mild flavor. Ricotta is rich in protein while being lower in salt and fat than many other cheese types.",
        image: "https://images.unsplash.com/photo-1551460188-2dace9f2fed3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 48,
        name: "Butter",
        category: "dairy",
        calories: 102,
        nutrients: {
            protein: 0.1,
            carbs: 0.1,
            fat: 11.5,
            fiber: 0,
            vitaminA: 11,
            vitaminC: 0,
            vitaminD: 1,
            vitaminE: 2,
            calcium: 0,
            iron: 0,
            potassium: 0,
            magnesium: 0,
            omega3: 0,
            antioxidants: 1
        },
        description: "Dairy product made from churned cream with high fat content. Butter contains fat-soluble vitamins and compounds that support hormone production.",
        image: "https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 49,
        name: "Sour Cream",
        category: "dairy",
        calories: 57,
        nutrients: {
            protein: 0.7,
            carbs: 1.3,
            fat: 5.6,
            fiber: 0,
            vitaminA: 5,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 2,
            iron: 0,
            potassium: 1,
            magnesium: 0,
            omega3: 0,
            antioxidants: 0
        },
        description: "Fermented dairy product with tangy flavor. Sour cream contains probiotics that can support digestive health and immune function.",
        image: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    },
    {
        id: 50,
        name: "Parmesan",
        category: "dairy",
        calories: 110,
        nutrients: {
            protein: 10,
            carbs: 0.9,
            fat: 7.3,
            fiber: 0,
            vitaminA: 6,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 1,
            calcium: 33,
            iron: 1,
            potassium: 1,
            magnesium: 2,
            omega3: 0,
            antioxidants: 1
        },
        description: "Hard, aged cheese with intense flavor and high calcium content. Parmesan is one of the most nutrient-dense cheeses, supporting bone health.",
        image: "https://images.unsplash.com/photo-1528747045269-390fe33c19f2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=80"
    }
];
